.TH EBSMOUNT 1 "14 Jun 2010"

.SH NAME
ebsmount-manual - Simulates udev add trigger

.SH DESCRIPTION
See: /usr/share/doc/ebsmount/docs/README

.SH SYNOPSIS
.B ebsmount-manual [-opts] <device>
.TP
See: ebsmount-manual --help

.SH FILES
.B /etc/ebsmount.conf

.SH SEE ALSO
.BR ebsmount-udev(8)

.SH AUTHOR
Alon Swartz <alon@turnkeylinux.org>
