.TH EBSMOUNT 8 "14 Jun 2010"

.SH NAME
ebsmount-udev - Triggered by udev on EBS attach and detach

.SH DESCRIPTION
See: /usr/share/doc/ebsmount/docs/README

.SH SYNOPSIS
.B ebsmount-udev <action>
.TP
See: ebsmount-udev --help

.SH FILES
.B /etc/ebsmount.conf

.SH SEE ALSO
.BR ebsmount-manual(1)

.SH AUTHOR
Alon Swartz <alon@turnkeylinux.org>
